---
homebrew_install_path: /usr/local/homebrew
homebrew_installed_packages:
  - git
  - wget
  - dockutil
  - zsh 
  - tree

homebrew_taps:
  - caskroom/cask
  - caskroom/versions

homebrew_cask_apps:
  - google-chrome
  - firefox
  - vagrant
  - virtualbox
  - visual-studio-code
  - xquartz
  - iterm2

dockitems_to_remove:
  - Mail
  - Safari
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iTunes
  - iBooks
  - App Store
  - Pages
  - Numbers
  - Keynote
  - Calendar

dockitems_to_persist:
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 1
  - name: VirtualBox
    path: /Applications/VirtualBox.app
    pos: 5
  - name: Terminal
    path: /Applications/Utilities/Terminal.app
    pos: 6
  - name: ThinLinc Client.app
    path: "/Applications/ThinLinc Client.app"
    pos: 7
  - name: VSCode
    path: "/Applications/Visual Studio Code.app"
    pos: 8

